#!/bin/bash

VAST=$(realpath .json/vast.json);
TMAP=$(realpath .json/tmap.json);
TM3D=$(realpath .json/tm3d.json);

[[ -z "$1" ]] && echo "e.g. $0 ~/src/foo/bar/" && exit 1;

echo "Parsing TS and generating AST in $VAST";
(cd ../ts-ast && node jsbin $1 > $VAST) || exit 1;

echo "Converting AST into a treemap in $TMAP";
(cd ../treemap && node index $VAST > $TMAP) || exit 1;

echo "Generating a 3D treemap layout in $TM3D";
(cd ../tm3d && node index $TMAP > $TM3D) || exit 1;
